recipes:
    global:
        - applications::ssh_config
        - dotfiles::vim
        - dotfiles::workspace
    mac_os_x:
        - applications::sublime_text_3
        - applications::gnu-tar
        - osxdefaults::set_terminal_profile
        - osxdefaults::add_a_context_menu_item_for_showing_the_web_inspector_in_web_views
        - osxdefaults::disable_press-and-hold_for_keys_in_favor_of_key_repeat
        - osxdefaults::set_a_blazingly_fast_keyboard_repeat_rate
        - osxdefaults::disable_disk_image_verification
        - osxdefaults::disable_gatekeeper
        - osxdefaults::disable_front_row
        - osxdefaults::enable_assistive_devices
        - osxdefaults::enable_full_keyboard_access_for_all_controls
        - osxdefaults::increase_window_resize_speed_for_cocoa_applications
        - osxdefaults::speed_up_mission_control_animations
        - osxdefaults::tap_to_click
        - osxdefaults::do_not_show_dashboard_as_a_space
        - osxdefaults::prevent_time_machine_from_prompting_to_use_new_hard_drives_as_backup_volume
        - osxdefaults::finder_allow_text_selection_in_quick_look
        - osxdefaults::finder_display_full_path
        - osxdefaults::finder_use_column_view_in_all_finder_windows_by_default
        - osxdefaults::finder_new_finder_windows_shows_homefolder
        - osxdefaults::finder_automatically_open_a_new_finder_window_when_a_volume_is_mounted
        - osxdefaults::finder_disable_the_warning_before_emptying_the_trash
        - osxdefaults::finder_disable_the_warning_when_changing_a_file_extension
        - osxdefaults::finder_search_the_current_folder_by_default
        - osxdefaults::finder_unhide_home
attributes:
    homebrewalt:
        apps:
            - fswatch
            - git
            - git-extras
            - git-flow
            - htop-osx
            - httpie
            - imagemagick
            - jq
            - pyenv
            - pyenv-virtualenv
            - pwgen
            - siege
            - watch
            - wget
            - xmlstarlet
        cask_apps:
            - evernote
            - imageoptim
            - imagealpha
            - sequel-pro
            - superduper
            - vagrant-manager
            - vagrant
            - virtualbox
            - chefdk
            - sourcetree
            - slack
    nodejs:
        apps:
            - uglify-js
            - uglifycss
            - bower
            - less
            - less-plugin-autoprefix
            - browserify
    gems:
        - sass
        - git-up
        - kstrano
        - deliver
        - crafter
    sublime_text_packages:
        -
            name: SublimeLinter
            source: https://github.com/SublimeLinter/SublimeLinter3.git
            branch: master
        -
            name: SideBarEnhancements
            source: https://github.com/titoBouzout/SideBarEnhancements
            branch: st3
        -
            name: GitGutter
            source: https://github.com/jisaacks/GitGutter.git
            branch: master
        -
            name: BracketHighlighter
            source: https://github.com/facelessuser/BracketHighlighter.git
            branch: master
        -
            name: Theme - Flatland
            source: git://github.com/thinkpixellab/flatland.git
            branch: master
        -
            name: Base16
            source: https://github.com/chriskempson/base16-textmate.git
            branch: master
        -
            name: ApplySyntax
            source: https://github.com/facelessuser/ApplySyntax.git
            branch: master
        -
            name: DocBlockr
            source: https://github.com/spadgos/sublime-jsdocs.git
            branch: master
    sublime_text:
        theme: "Flatland Dark.sublime-theme"
        color_scheme: "Packages/Theme - Flatland/Flatland Monokai.tmTheme"
